#!/bin/sh
clear
echo
echo "*** [31mJQ6500 toolkit[0m ***"
echo
while true; do
    echo "Looking for a matching MP3-module..."
    jq6500/jq6500 -l
    echo
    echo "1...Repair 32MBit Module"
    echo "2...Repair 16Mbit Module"
    echo "3...Look again for devices"
    echo "4...Exit"
    echo
    read -p "Choice: " choice
    case "$choice" in
        1) jq6500/jq6500 -r -o 0 jq6500/ISO_32MBit/MusicDownload.iso
           echo
           echo "Done."
           echo "Plug in another device. Press any key."
           read
        ;;
        2) jq6500/jq6500 -r -o 0 jq6500/ISO_16MBit/MusicDownload.iso
           echo
           echo "Done."
           echo "Plug in another device. Press any key."
           read
        ;;
        3) sleep 3
        ;;
        4) break
        ;;
        *) echo "Unknown option."
    esac
done
echo
echo "Bye! Enter [32m./toolkit[0m to start again."
echo "For German keyboard layout enter [32mloadkeys de[0m"
echo


